FROM ubuntu:14.04

MAINTAINER Sean Kruzel <sean.kruzel@gmail.com>

#install java
RUN apt-get update
RUN apt-get install -y curl wget vim unzip

# Source: http://ofirm.wordpress.com/2014/01/05/creating-a-virtualized-fully-distributed-hadoop-cluster-using-linux-containers/

RUN apt-get update

# Get add-apt-repositoy command.
RUN apt-get install -y software-properties-common

# Add Oracle Java repository.
RUN add-apt-repository -y ppa:webupd8team/java

# Add flag file to automate Oracle Java installation
RUN echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
RUN echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections

# Install Oracle Java
RUN apt-get update && apt-get install -y oracle-java7-installer

ENV JAVA_HOME /usr/lib/jvm/java-7-oracl

#RUN wget http://download.oracle.com/otn-pub/java/jdk/7u67-b01/jdk-7u67-linux-x64.tar.gz > jdk-7u67-linux-x4.tar.gz
#RUN 
#  apt-get install -y   
#try to add jps
#RUN apt-get install -y openjdk-7-jdk-devel

#add JAVA_HOME to path
ENV PATH $JAVA_HOME:$PATH

WORKDIR /opt/titan-0.5.0-hadoop2

RUN curl -o /opt/titan.zip http://s3.thinkaurelius.com/downloads/titan/titan-0.5.0-hadoop2.zip

RUN unzip /opt/titan.zip -d /opt/ && \
    rm /opt/titan.zip

ADD rexster-titan.xml.template /opt/titan-0.5.0-hadoop2/

RUN echo "version 0.11"

ADD run.sh /opt/titan-0.5.0-hadoop2/

EXPOSE 8182
EXPOSE 8183
EXPOSE 8184


CMD ["/bin/sh", "-e", "/opt/titan-0.5.0-hadoop2/run.sh"]
